### ISSUE TITLE
Websocket error on console log

### ISSUE THREAD

**Issue by ruleechen** [ringcentral/ringcentral-extensible#28]
rest.js:40
Uncaught (in promise) DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at WebSocketExtension.request (file:///D:/rc/git/integration-apps/packages/lyncintegration/app/views/main/index.js:85407:13)
    at Subscription.subscribe (file:///D:/rc/git/integration-apps/packages/lyncintegration/app/views/main/index.js:85485:49)
    at WebSocketExtension.connect (file:///D:/rc/git/integration-apps/packages/lyncintegration/app/views/main/index.js:85319:36)
    at async WebSocketExtension.recover (file:///D:/rc/git/integration-apps/packages/lyncintegration/app/views/main/index.js:85250:13)

![image](https://user-images.githubusercontent.com/907369/118070232-1a457700-b3d8-11eb-932e-c3c138ae63bf.png)

**Comment by ruleechen** [comment]
See another error

![image](https://user-images.githubusercontent.com/907369/118074162-f9811f80-b3df-11eb-8cd5-523a102e3260.png)

**Comment by tylerlong** [comment]
Released 0.9.9

**Comment by tylerlong** [comment]
I think the second error could be safely ignored. 
Because it is invoked by timer, and no matter there is error or not, WS will be closed.
Let's ignore it for now. 
Please create new ticket if you see such errors a lot.

**Comment by ruleechen** [comment]
> I think the second error could be safely ignored.
> Because it is invoked by timer, and no matter there is error or not, WS will be closed.
> Let's ignore it for now.
> Please create new ticket if you see such errors a lot.

Yes, agreed. Let's ignore it for now.
